import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://test3.busseat.lk/sign-in');
  await page.getByPlaceholder('Enter username').click();
  await page.getByPlaceholder('Enter username').fill('nimda');
  await page.getByPlaceholder('Enter password').click();
  await page.getByPlaceholder('Enter password').fill('xcr967l2r9hf58zc');
  await page.getByRole('button', { name: 'Sign in' }).click();
  //await page.getByRole('link', { name: ' Home Page' }).click();
  await page.getByRole('button', { name: ' Buses' }).click();
  await page.getByRole('link', { name: 'Create Bus' }).click();
  await page.getByPlaceholder('Enter bus name').click();
  await page.getByPlaceholder('Enter bus name').fill('Bus New 1');
  await page.getByPlaceholder('Enter bus number').click();
  await page.getByPlaceholder('Enter bus number').fill('NP ND 7777');
  await page.getByLabel('Bus Type').selectOption('SUPER_LUXURY');
  await page.getByPlaceholder('Select bus operator').click();
  await page.getByText('Abi Travels').click();
  await page.getByRole('cell', { name: 'Select the facility' }).locator('div').nth(1).click();
  await page.getByRole('cell', { name: 'Hotlines (10 Digits) ' }).click();
  await page.getByPlaceholder(' eg: 0771234567 or').fill('0212224567');
  await page.getByPlaceholder('Enter the number of seats').click();
  await page.getByPlaceholder('Enter the number of seats').fill('20');
  await page.getByLabel('Seat Layout Number Type').selectOption('ALPHA_NUMERIC');
  await page.getByRole('button', { name: 'Generate Seats' }).click();
  await page.locator('#seatNumber_0').click();
  await page.locator('#seatNumber_0').fill('1');
  await page.locator('#seatNumber_1').click();
  await page.locator('#seatNumber_1').fill('2');
  await page.locator('#seatNumber_2').click();
  await page.locator('#seatNumber_2').fill('3');
  await page.locator('#seatNumber_3').click();
  await page.locator('#seatNumber_3').fill('4');
  await page.locator('#seatNumber_4').click();
  await page.locator('#seatNumber_4').fill('5');
  await page.locator('#seatNumber_5').click();
  await page.locator('#seatNumber_5').fill('6');
  await page.locator('#seatNumber_6').click();
  await page.locator('#seatNumber_6').fill('7');
  await page.locator('#seatNumber_7').click();
  await page.locator('#seatNumber_7').fill('8');
  await page.locator('#seatNumber_8').click();
  await page.locator('#seatNumber_8').fill('9');
  await page.locator('#seatNumber_9').click();
  await page.locator('#seatNumber_9').fill('10');
  await page.locator('#seatNumber_10').click();
  await page.locator('#seatNumber_10').fill('11');
  await page.locator('#seatNumber_11').click();
  await page.locator('#seatNumber_11').fill('12');
  await page.locator('#seatNumber_12').click();
  await page.locator('#seatNumber_12').fill('13');
  await page.locator('#seatNumber_13').click();
  await page.locator('#seatNumber_13').fill('14');
  await page.locator('#tr_14 > td').first().click();
  await page.locator('#seatNumber_14').fill('15');
  await page.locator('#seatNumber_15').click();
  await page.locator('#seatNumber_15').fill('16');
  await page.locator('#seatNumber_16').click();
  await page.locator('#seatNumber_16').fill('17');
  await page.locator('#tr_17 > td').first().click();
  await page.locator('#seatNumber_17').fill('18');
  await page.locator('#seatNumber_18').click();
  await page.locator('#seatNumber_18').fill('19');
  await page.locator('#seatNumber_19').click();
  await page.locator('#seatNumber_19').fill('20');
  await page.locator('#row_0').click();
  await page.locator('#row_0').fill('1');
  await page.locator('#row_1').click();
  await page.locator('#row_1').fill('1');
  await page.locator('#row_2').click();
  await page.locator('#row_2').fill('1');
  await page.locator('#row_3').click();
  await page.locator('#row_3').fill('1');
  await page.locator('#row_4').click();
  await page.locator('#row_4').fill('2');
  await page.locator('#row_5').click();
  await page.locator('#row_5').fill('2');
  await page.locator('#row_6').click();
  await page.locator('#row_6').fill('2');
  await page.locator('#row_7').click();
  await page.locator('#row_7').fill('2');
  await page.locator('#row_8').click();
  await page.locator('#row_8').fill('3');
  await page.locator('#row_9').click();
  await page.locator('#row_9').fill('3');
  await page.locator('#row_10').click();
  await page.locator('#row_10').fill('3');
  await page.locator('#row_11').click();
  await page.locator('#row_11').fill('3');
  await page.locator('#row_12').click();
  await page.locator('#row_12').fill('4');
  await page.locator('#row_13').click();
  await page.locator('#row_13').fill('4');
  await page.locator('#row_14').click();
  await page.locator('#row_14').fill('4');
  await page.locator('#row_15').click();
  await page.locator('#row_15').fill('4');
  await page.locator('#row_16').click();
  await page.locator('#row_16').fill('5');
  await page.locator('#row_17').click();
  await page.locator('#row_17').fill('5');
  await page.locator('#row_18').click();
  await page.locator('#row_18').fill('5');
  await page.locator('#row_19').click();
  await page.locator('#row_19').fill('5');
  await page.locator('#group_0').click();
  await page.locator('#group_0').fill('1');
  await page.locator('#group_1').click();
  await page.locator('#group_1').fill('1');
  await page.locator('#group_2').click();
  await page.locator('#group_2').fill('2');
  await page.locator('#group_3').click();
  await page.locator('#group_3').fill('2');
  await page.locator('#group_4').click();
  await page.locator('#group_4').fill('1');
  await page.locator('#group_5').click();
  await page.locator('#group_5').fill('1');
  await page.locator('#group_6').click();
  await page.locator('#group_6').fill('2');
  await page.locator('#group_7').click();
  await page.locator('#group_7').fill('2');
  await page.locator('#group_8').click();
  await page.locator('#group_8').fill('1');
  await page.locator('#group_9').click();
  await page.locator('#group_9').fill('1');
  await page.locator('#group_10').click();
  await page.locator('#group_10').fill('2');
  await page.locator('#group_11').click();
  await page.locator('#group_11').fill('2');
  await page.locator('#tr_12 > td:nth-child(4)').click();
  await page.locator('#group_12').fill('1');
  await page.locator('#group_13').click();
  await page.locator('#group_13').fill('1');
  await page.locator('#group_14').click();
  await page.locator('#group_14').fill('2');
  await page.locator('#group_15').click();
  await page.locator('#group_15').fill('2');
  await page.locator('#group_16').click();
  await page.locator('#group_16').fill('1');
  await page.locator('#group_17').click();
  await page.locator('#group_17').fill('1');
  await page.locator('#group_18').click();
  await page.locator('#group_18').fill('2');
  await page.locator('#group_19').click();
  await page.locator('#group_19').fill('2');
   await page.getByRole('button', { name: 'Create Bus' }).click();
  await page.goto('https://test3.busseat.lk/bus-manager/create');
});