import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://test3.busseat.lk/sign-in');
  await page.getByPlaceholder('Enter username').click();
  await page.getByPlaceholder('Enter username').fill('nimda');
  await page.getByPlaceholder('Enter password').click();
  await page.getByPlaceholder('Enter password').fill('xcr967l2r9hf58zc');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('button', { name: ' Accounts' }).click();
  await page.getByRole('link', { name: 'Manage Discounts' }).click();
  await page.getByLabel('Create New').click();
  await page.locator('#user-type-input').selectOption('PASSENGER');
  await page.locator('#payment-instrument-input').selectOption('654a12d810c6264f69764e78');
  await page.getByPlaceholder('Select the operator').click();
  await page.locator('div').filter({ hasText: /^ALL$/ }).click();
  await page.getByPlaceholder('Select the route').click();
  await page.getByText('|| Colombo-Kandy').click();
  await page.locator('#bus-type-input').selectOption('ALL');
  await page.getByLabel('Discount\n                                    Category').selectOption('DISCOUNT_BUS_FARE_OPERATOR');
  await page.getByLabel('Discount Type').selectOption('PERCENTAGE');
  await page.getByPlaceholder('Enter the discount value').click();
  await page.getByPlaceholder('Enter the discount value').fill('5');
  await page.getByPlaceholder('Select start date.').click();
  await page.getByRole('cell', { name: '9' }).first().click();
  await page.getByRole('cell', { name: '9' }).first().click();
  await page.getByRole('cell', { name: '9' }).first().click();
  await page.getByText('Cancel Create').click();
  await page.getByPlaceholder('Select end date.').click();
  await page.getByRole('cell', { name: '16' }).click();
  await page.getByText('Cancel Create').click();
  await page.locator('div').filter({ hasText: /^1 \|\| Colombo-Kandy$/ }).first().click();
  await page.getByText('ALL', { exact: true }).nth(3).click();
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await page.getByLabel('Create New').click();
  await page.locator('#user-type-input').selectOption('ANONYMOUS');
  await page.locator('#payment-instrument-input').selectOption('654a12d810c6264f69764e78');
  await page.getByPlaceholder('Select the operator').click();
  await page.getByText('ALL', { exact: true }).first().click();
  await page.getByPlaceholder('Select the route').click();
  await page.getByText('|| Colombo-Kandy').click();
  await page.locator('#bus-type-input').selectOption('ALL');
  await page.getByLabel('Discount\n                                    Category').selectOption('DISCOUNT_BUS_FARE_PLATFORM');
  await page.getByLabel('Discount Type').selectOption('FIXED');
  await page.getByPlaceholder('Enter the discount value').click();
  await page.getByLabel('Discount Type').selectOption('PERCENTAGE');
  await page.getByPlaceholder('Enter the discount value').click();
  await page.getByPlaceholder('Enter the discount value').fill('5');
  await page.getByPlaceholder('Select start date.').click();
  await page.getByRole('cell', { name: '9' }).first().click();
  await page.locator('#discount-modal div').filter({ hasText: 'User Type Select the user' }).nth(2).click();
  await page.getByPlaceholder('Select end date.').click();
  await page.getByRole('cell', { name: '16' }).click();
  await page.getByText('Cancel Create').click();
  await page.locator('div').filter({ hasText: /^1 \|\| Colombo-Kandy$/ }).first().click();
  await page.getByText('ALL', { exact: true }).nth(3).click();
  await page.getByRole('button', { name: 'Create', exact: true }).click();
});