import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://uat.medster.app/login');
  await page.getByPlaceholder('Enter your email').click();
  await page.getByPlaceholder('Enter your email').fill('vithursiha@3axislabs.com');
  await page.getByPlaceholder('Enter your password').click();
  await page.getByPlaceholder('Enter your password').fill('Password@123');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('button', { name: 'Create Organization' }).click();
  await page.locator('div').filter({ hasText: /^Name \*Address \*Phone Number \*Phone$/ }).getByPlaceholder('Enter name').click();
  await page.locator('div').filter({ hasText: /^Name \*Address \*Phone Number \*Phone$/ }).getByPlaceholder('Enter name').fill('Clinic 1');
  await page.locator('div').filter({ hasText: /^Name \*Address \*Phone Number \*Phone$/ }).getByPlaceholder('Enter your address').click();
  await page.locator('div').filter({ hasText: /^Name \*Address \*Phone Number \*Phone$/ }).getByPlaceholder('Enter your address').fill('Bramp');
  await page.locator('div:nth-child(26) > div:nth-child(3) > .pac-item-query').click();
  await page.locator('div').filter({ hasText: /^Name \*Address \*Phone Number \*Phone$/ }).getByPlaceholder('Enter phone number').click();
  await page.locator('div').filter({ hasText: /^Name \*Address \*Phone Number \*Phone$/ }).getByPlaceholder('Enter phone number').fill('+1 (111) 111-11111');
  await page.locator('div').filter({ hasText: /^Name \*Email \*$/ }).getByPlaceholder('Enter name').click();
  await page.locator('div').filter({ hasText: /^Name \*Email \*$/ }).getByPlaceholder('Enter name').fill('David Villa');
  await page.locator('div').filter({ hasText: /^Name \*Email \*$/ }).getByPlaceholder('Enter email').click();
  await page.locator('div').filter({ hasText: /^Name \*Email \*$/ }).getByPlaceholder('Enter email').fill('dv@mailinator.com');
  await page.locator('#administrator').click();
  await page.locator('#administrator').fill('David Villa');
  await page.locator('div').filter({ hasText: /^Name \*Email \*Phone Number \*PhoneAddress \*$/ }).getByPlaceholder('Enter email').click();
  await page.locator('div').filter({ hasText: /^Name \*Email \*Phone Number \*PhoneAddress \*$/ }).getByPlaceholder('Enter email').fill('dv2@mailinator.com');
  await page.locator('div').filter({ hasText: /^Name \*Email \*Phone Number \*PhoneAddress \*$/ }).getByPlaceholder('Enter phone number').click();
  await page.locator('div').filter({ hasText: /^Name \*Email \*Phone Number \*PhoneAddress \*$/ }).getByPlaceholder('Enter phone number').fill('+1 (123) 456-7891');
  await page.locator('div').filter({ hasText: /^Name \*Email \*Phone Number \*PhoneAddress \*$/ }).getByPlaceholder('Enter your address').click();
  await page.locator('div').filter({ hasText: /^Name \*Email \*Phone Number \*PhoneAddress \*$/ }).getByPlaceholder('Enter your address').fill('Brampton');
  await page.locator('div:nth-child(227) > div').first().click();
  await page.locator('div').filter({ hasText: /^Name \*Email \*Phone Number \*PhoneAddress \*$/ }).getByPlaceholder('Enter your address').click();
  await page.locator('div:nth-child(229) > div:nth-child(2) > .pac-item-query').click();
  await page.locator('div').filter({ hasText: /^Name \*Email \*Phone Number \*PhoneAddress \*$/ }).getByPlaceholder('Enter your address').click();
  await page.locator('div:nth-child(231) > div:nth-child(2) > .pac-item-query').click();
  await page.locator('#insurance-provider').selectOption('HST');
  await page.getByPlaceholder('Enter HST No.').click();
  await page.getByPlaceholder('Enter HST No.').fill('2222');
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await page.getByRole('button', { name: 'Open user menu V' }).click();
  await page.getByRole('link', { name: 'Sign out' }).click();
});