import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://uat.medster.app/login');
  await page.getByPlaceholder('Enter your email').click();
  await page.getByPlaceholder('Enter your email').fill('vithursiha@3axislabs.com');
  await page.getByPlaceholder('Enter your password').click();
  await page.getByPlaceholder('Enter your password').fill('Axis@12345');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('button', { name: 'Create Organization' }).click();
  await page.locator('div').filter({ hasText: /^Name \*Address \*Phone Number \*Phone$/ }).getByPlaceholder('Enter name').click();
  await page.locator('div').filter({ hasText: /^Name \*Address \*Phone Number \*Phone$/ }).getByPlaceholder('Enter name').fill('Ottawa Medical Clinic');
  await page.locator('div').filter({ hasText: /^Name \*Address \*Phone Number \*Phone$/ }).getByPlaceholder('Enter address').click();
  await page.locator('div').filter({ hasText: /^Name \*Address \*Phone Number \*Phone$/ }).getByPlaceholder('Enter address').fill('Ottawa');
  await page.locator('div:nth-child(54) > div').first().click();
  await page.locator('div').filter({ hasText: /^Name \*Address \*Address is invalidPhone Number \*Phone$/ }).getByPlaceholder('Enter phone number').click();
  await page.locator('div').filter({ hasText: /^Name \*Address \*Address is invalidPhone Number \*Phone$/ }).getByPlaceholder('Enter address').click();
  await page.locator('div:nth-child(56) > div').first().click();
  await page.locator('div').filter({ hasText: /^Name \*Address \*Phone Number \*PhonePhone number is required$/ }).getByPlaceholder('Enter phone number').click();
  await page.locator('div').filter({ hasText: /^Name \*Address \*Phone Number \*PhonePhone number is required$/ }).getByPlaceholder('Enter phone number').fill('+1 (123) 456-7890');
  await page.locator('div').filter({ hasText: /^Name \*Email \*$/ }).getByPlaceholder('Enter name').click();
  await page.locator('div').filter({ hasText: /^Name \*Email \*$/ }).getByPlaceholder('Enter name').fill('R P Singh');
  await page.locator('div').filter({ hasText: /^Name \*Email \*$/ }).getByPlaceholder('Enter email').click();
  await page.locator('div').filter({ hasText: /^Name \*Email \*$/ }).getByPlaceholder('Enter email').fill('rps@mailinator.com');
  await page.locator('#administrator').click();
  await page.locator('#administrator').fill('R P Singh');
  await page.locator('div').filter({ hasText: /^Name \*Email \*Phone Number \*PhoneAddress \*$/ }).getByPlaceholder('Enter email').click();
  await page.locator('div').filter({ hasText: /^Name \*Email \*Phone Number \*PhoneAddress \*$/ }).getByPlaceholder('Enter email').fill('rpd@mailinator.com');
  await page.locator('div').filter({ hasText: /^Name \*Email \*Phone Number \*PhoneAddress \*$/ }).getByPlaceholder('Enter phone number').click();
  await page.locator('div').filter({ hasText: /^Name \*Email \*Phone Number \*PhoneAddress \*$/ }).getByPlaceholder('Enter phone number').fill('+1 (098) 765-4321');
  await page.locator('div').filter({ hasText: /^Name \*Email \*Phone Number \*PhoneAddress \*$/ }).getByPlaceholder('Enter address').click();
  await page.locator('div').filter({ hasText: /^Name \*Email \*Phone Number \*PhoneAddress \*$/ }).getByPlaceholder('Enter address').fill('On');
  await page.locator('div:nth-child(220) > div:nth-child(3) > .pac-item-query').click();
  await page.locator('div').filter({ hasText: /^Name \*Email \*Phone Number \*PhoneAddress \*Address is invalid$/ }).getByPlaceholder('Enter address').click();
  await page.locator('div').filter({ hasText: /^Name \*Email \*Phone Number \*PhoneAddress \*Address is invalid$/ }).getByPlaceholder('Enter address').click();
  await page.locator('div:nth-child(222) > div:nth-child(3)').click();
  await page.locator('#insurance-provider').selectOption('HST');
  await page.getByPlaceholder('Enter HST No.').click();
  await page.getByPlaceholder('Enter HST No.').fill('7410');
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await page.getByRole('button', { name: 'Open user menu V' }).click();
  await page.getByRole('link', { name: 'Sign out' }).click();
});