import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://uat.medster.app/login');
  await page.getByPlaceholder('Enter your email').click();
  await page.getByPlaceholder('Enter your email').fill('kokulan@3axislabs.com');
  await page.getByPlaceholder('Enter your password').click();
  await page.getByPlaceholder('Enter your password').fill('Password@123');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'Paycycles' }).click();
  await page.getByRole('link', { name: 'My Team' }).click();
  await page.getByRole('button', { name: 'Add User' }).click();
  await page.getByPlaceholder('Enter name').click();
  await page.getByPlaceholder('Enter name').fill('Admin JD2');
  await page.getByPlaceholder('Enter email').click();
  await page.getByPlaceholder('Enter email').fill('amd2@mailinator.com');
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('button', { name: 'Add User' }).click();
  await page.locator('div').filter({ hasText: /^Provider$/ }).click();
  await page.getByPlaceholder('Enter name').click();
  await page.getByPlaceholder('Enter name').fill('Doctor Strange 2');
  await page.getByPlaceholder('Enter job title').click();
  await page.getByPlaceholder('Enter job title').fill('Magician');
  await page.getByPlaceholder('Enter email').click();
  await page.getByPlaceholder('Enter email').fill('dsm2@mailinator.com');
  await page.getByPlaceholder('Enter your address').click();
  await page.getByPlaceholder('Enter your address').fill('Kand');
  await page.locator('div:nth-child(57) > div:nth-child(3) > span:nth-child(3)').click();
  await page.getByPlaceholder('Enter phone number').click();
  await page.getByPlaceholder('Enter phone number').fill('+1 (456) 789-11111');
  await page.getByPlaceholder('Solo OHIP').click();
  await page.getByPlaceholder('Solo OHIP').fill('10');
  await page.getByPlaceholder('Access Bonus').click();
  await page.getByPlaceholder('Access Bonus').fill('20');
  await page.getByPlaceholder('FHO Group Number Payment').click();
  await page.getByPlaceholder('FHO Group Number Payment').fill('30');
  await page.getByPlaceholder('Third party payment').click();
  await page.getByPlaceholder('Third party payment').fill('40');
  await page.getByPlaceholder('Enter OHIP Billing No.').click();
  await page.getByPlaceholder('Enter OHIP Billing No.').fill('A1234');
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByLabel('close').click();
});