import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://medster.app/login');
  await page.locator('div').filter({ hasText: /^Email Address \*$/ }).nth(1).click();
  await page.getByPlaceholder('Enter your email').fill('kokulan@3axislabs.com');
  await page.getByPlaceholder('Enter your password').click();
  await page.getByPlaceholder('Enter your password').fill('Password@123');
  await page.getByPlaceholder('Enter your password').press('Enter');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'Paycycles' }).click();
  await page.getByRole('button', { name: 'Create Paycycle' }).click();
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await page.getByRole('row', { name: 'Jan 2024 CA$0.00 OPEN Edit' }).locator('span').click();
  await page.getByRole('button', { name: 'Add Transaction' }).click();
  await page.getByPlaceholder('Solo OHIP').click();
  await page.getByPlaceholder('Solo OHIP').fill('1000');
  await page.getByPlaceholder('Access Bonus').click();
  await page.getByPlaceholder('Access Bonus').fill('850');
  await page.getByPlaceholder('FHO Group Number Payment').click();
  await page.getByPlaceholder('FHO Group Number Payment').fill('1050');
  await page.getByPlaceholder('3rd Party Payment').click();
  await page.getByPlaceholder('3rd Party Payment').fill('1000');
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('button', { name: 'Add Transaction' }).click();
  await page.locator('#provider').selectOption('6246bc91-2832-4023-bb69-7a56e4ff8f74');
  await page.locator('div').filter({ hasText: /^Solo OHIP\$$/ }).first().click();
  await page.getByPlaceholder('Solo OHIP').fill('500');
  await page.getByPlaceholder('Access Bonus').click();
  await page.getByPlaceholder('Access Bonus').fill('900');
  await page.getByPlaceholder('FHO Group Number Payment').click();
  await page.getByPlaceholder('FHO Group Number Payment').fill('410');
  await page.getByPlaceholder('3rd Party Payment').click();
  await page.getByPlaceholder('3rd Party Payment').fill('990');
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('button', { name: 'Add Transaction' }).click();
  await page.locator('#provider').selectOption('e0ccaf54-9632-4c83-8607-0d05322d14f8');
  await page.getByPlaceholder('Solo OHIP').click();
  await page.getByPlaceholder('Solo OHIP').fill('456');
  await page.getByPlaceholder('Access Bonus').click();
  await page.getByPlaceholder('Access Bonus').fill('564');
  await page.getByPlaceholder('FHO Group Number Payment').click();
  await page.getByPlaceholder('FHO Group Number Payment').fill('580');
  await page.getByPlaceholder('3rd Party Payment').click();
  await page.getByPlaceholder('3rd Party Payment').fill('250');
  await page.getByRole('button', { name: 'Create' }).click();
  /*await page.locator('#provider').selectOption('ee24a946-5897-417f-af16-30acadf533f9');
  await page.getByPlaceholder('Solo OHIP').click();
  await page.getByPlaceholder('Solo OHIP').fill('456');
  await page.getByPlaceholder('Access Bonus').click();
  await page.getByPlaceholder('Access Bonus').fill('564');
  await page.getByPlaceholder('FHO Group Number Payment').click();
  await page.getByPlaceholder('FHO Group Number Payment').fill('580');
  await page.getByPlaceholder('3rd Party Payment').click();
  await page.getByPlaceholder('3rd Party Payment').fill('250');
  await page.getByRole('button', { name: 'Create' }).click();*/
  await page.getByRole('button', { name: 'Paycycle Adjustments' }).click();
  await page.getByRole('button', { name: 'Add Paycycle Adjustment' }).click();
  await page.getByPlaceholder('Enter Paycycle Adjustment').click();
  await page.getByPlaceholder('Enter Paycycle Adjustment').fill('Nurse Fee');
  await page.getByPlaceholder('Amount').click();
  await page.getByPlaceholder('Amount').fill('25');
  await page.getByLabel('Adjustment includes HST').check();
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('button', { name: 'Add Paycycle Adjustment' }).click();
  await page.getByPlaceholder('Enter Paycycle Adjustment').click();
  await page.getByPlaceholder('Enter Paycycle Adjustment').fill('Party Expenses');
  await page.getByPlaceholder('Amount').click();
  await page.getByPlaceholder('Amount').fill('1000');
  await page.getByLabel('Split Across Billable').check();
  await page.getByText('Adjustment includes HSTAdjustment included in Management Fee').click();
  await page.getByLabel('Adjustment includes HST').check();
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('button', { name: 'Add Paycycle Adjustment' }).click();
  await page.getByPlaceholder('Enter Paycycle Adjustment').click();
  await page.getByPlaceholder('Enter Paycycle Adjustment').fill('Maintain Fee');
  await page.getByPlaceholder('Amount').click();
  await page.getByPlaceholder('Amount').fill('1500');
  await page.getByLabel('Split Across Billable').check();
  await page.getByText('Add Paycycle AdjustmentCancelCreateAdjustment detailsDescription *Amount$How to').click();
  await page.locator('.checkbox-wrapper').first().click();
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('button', { name: 'Add Paycycle Adjustment' }).click();
  await page.getByPlaceholder('Enter Paycycle Adjustment').click();
  await page.getByPlaceholder('Enter Paycycle Adjustment').fill('Room Rent');
  await page.getByPlaceholder('Amount').click();
  await page.getByPlaceholder('Amount').fill('50');
  await page.getByLabel('Adjustment includes HST').check();
  await page.getByLabel('Adjustment included in').check();
  await page.getByRole('button', { name: 'Create' }).click();
  //await page.getByRole('button', { name: 'Close', exact: true }).click();
  //await page.getByRole('button', { name: 'Close Paycycle' }).click();
});