import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.locator('body').click();
  await page.goto('https://test.sharonbuslines.ca/');
  await page.locator('#menu').getByRole('link', { name: 'Get quote now' }).click();
  await page.getByPlaceholder('Enter your Company Name').click();
  await page.getByPlaceholder('Enter your Company Name').fill('Jack Daniels');
  await page.getByPlaceholder('Enter your Name').click();
  await page.getByPlaceholder('Enter your Name').fill('Demon');
  await page.getByPlaceholder('Enter your phone number, ex +').click();
  await page.getByPlaceholder('Enter your phone number, ex +').fill('+940779731605');
  await page.getByPlaceholder('Enter your Email').click();
  await page.getByPlaceholder('Enter your Email').fill('kokulan@3axislabs.com');
  await page.getByPlaceholder('Enter your Address Line 1').click();
  await page.getByPlaceholder('Enter your Address Line 1').fill('Alberto');
  await page.getByPlaceholder('Enter your Address Line 2').click();
  await page.getByPlaceholder('Enter your Address Line 2').fill('Del Rio');
  await page.getByPlaceholder('Enter your city').click();
  await page.getByPlaceholder('Enter your city').fill('Montrial');
  await page.getByPlaceholder('Enter your state').click();
  await page.getByPlaceholder('Enter your state').fill('Ontario');
  await page.getByPlaceholder('Enter your city').click();
  await page.getByPlaceholder('Enter your city').dblclick();
  await page.getByPlaceholder('Enter your city').click();
  await page.getByPlaceholder('Enter your city').dblclick();
  await page.getByPlaceholder('Enter your city').fill('Toronto');
  await page.getByPlaceholder('Enter your postal code').click();
  await page.getByPlaceholder('Enter your postal code').fill('M5J 2N8');
  await page.getByPlaceholder('Enter Number of passengers').click();
  await page.getByPlaceholder('Enter Number of passengers').fill('10');
  await page.getByLabel('One-way trip').check();
  await page.getByPlaceholder('Enter Depart from').click();
  await page.getByPlaceholder('Enter Depart from').fill('A');
  await page.getByPlaceholder('Enter Pickup location').click();
  await page.getByPlaceholder('Enter Pickup location').fill('B');
  await page.locator('#depart-from-date').fill('2024-01-29');
  await page.locator('#depart-from-time').click();
  await page.locator('#depart-from-time').fill('15:55');
  await page.locator('#pickup-location-date1').fill('2024-01-29');
  await page.locator('#pickup-location-time1').click();
  await page.locator('#pickup-location-time1').fill('15:55');
  await page.getByPlaceholder('Enter Return to').click();
  await page.getByPlaceholder('Enter Return to').fill('b');
  await page.locator('#return-to-date').fill('2024-01-29');
  await page.locator('#return-to-time').click();
  await page.locator('#return-to-time').fill('15:55');
  await page.locator('#drop-off-location-date1').fill('2024-01-29');
  await page.locator('#drop-off-location-time1').click();
  await page.locator('#drop-off-location-time1').fill('15:55');
  await page.getByPlaceholder('Enter Drop off location').click();
  await page.getByPlaceholder('Enter Drop off location').fill('c');
  await page.getByPlaceholder('Enter your note here...').click();
  await page.getByPlaceholder('Enter your note here...').fill('AAAA');
  await page.frameLocator('iframe[name="a-wn1hoh9wzb5w"]').getByLabel('I\'m not a robot').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Back to Home' }).click();
});