import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('about:blank');
  await page.goto('https://test3.busseat.lk/');
  await page.getByPlaceholder('Enter your departure station').click();
  await page.getByPlaceholder('Enter your departure station').fill('Jaff');
  await page.getByText('Jaffna').nth(2).click();
  await page.locator('div:nth-child(2) > .form-group > .selectize-control > .form-control').click();
  await page.getByPlaceholder('Enter your arrival station').fill('Colo');
  await page.getByText('Colombo', { exact: true }).nth(2).click();
  await page.getByPlaceholder('Select journey date').click();
  await page.getByRole('cell', { name: '30' }).click();
  await page.getByRole('button', { name: 'Find Buses' }).click();
  await page.locator('li').filter({ hasText: 'Colombo Bus 1 Super Luxury (' }).getByRole('link').click();
  await page.getByRole('checkbox', { name: '20', exact: true }).click();
  await page.getByRole('button', { name: 'F' }).click();
  await page.getByText('Passenger Name Mobile Number').click();
  await page.getByPlaceholder('Enter passenger name').click();
  await page.getByPlaceholder('Enter passenger name').fill('Jhosphine Langford');
  await page.getByPlaceholder('234 5678').click();
  await page.getByPlaceholder('234 5678').press('Insert');
  await page.getByPlaceholder('234 5678').press('Home');
  await page.getByPlaceholder('234 5678').press('Home');
  await page.getByPlaceholder('234 5678').click();
  await page.getByPlaceholder('234 5678').press('NumLock');
  await page.getByPlaceholder('234 5678').fill('0779731605');
  await page.getByPlaceholder('user@domain.com').click();
  await page.getByPlaceholder('user@domain.com').fill('kokulan13axislabs.com');
  await page.locator('.selectize-input').first().click();
  await page.getByText('Manipay Yard - 7:30 PM').click();
  await page.getByPlaceholder('Select your destination point').click();
  await page.getByText('Ratmalana - 5:50 AM').click();
  await page.getByRole('button', { name: 'Continue to pay' }).click();
  await page.getByRole('button', { name: 'Confirm and pay' }).click();
  await page.getByTestId('pomelopay-button').click();
  await page.getByLabel('I agree to the terms and').check();
  await page.getByTestId('pomelopay-button').click();
  await page.locator('div').filter({ hasText: /^Visa\/Mastercard$/ }).nth(1).click();
  await page.getByPlaceholder('Name on card').click();
  await page.getByPlaceholder('Name on card').fill('Samantha');
  await page.getByPlaceholder('Card Number').click();
  await page.getByPlaceholder('Card Number').fill('5099 9930 0011 6951');
  await page.getByPlaceholder('MM/YY').click();
  await page.getByPlaceholder('MM/YY').fill('03/27');
  await page.getByPlaceholder('CVV').click();
  await page.getByPlaceholder('CVV').fill('986');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.frameLocator('#pp-lightbox-iframe').getByRole('button', { name: 'Submit' }).click();
  //await page.goto('https://test3.busseat.lk/booking/20240514.100715.349.001/result');
});
