import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.locator('body').click();
  await page.goto('https://test3.busseat.lk/');
  await page.getByPlaceholder('Enter your departure station').click();
  await page.getByPlaceholder('Enter your departure station').fill('Jaffna');
  await page.getByPlaceholder('Enter your arrival station').fill('C');
  await page.getByText('Chillaw').nth(1).click();
  await page.locator('div').filter({ hasText: /^Chillaw$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Chillaw$/ }).nth(1).click();
  await page.getByLabel('TO').fill('Colo');
  await page.getByText('Colombo', { exact: true }).nth(2).click();
  await page.getByPlaceholder('Select journey date').click();
  await page.getByRole('cell', { name: '20', exact: true }).click();
  await page.goto('https://test3.busseat.lk/buses/Jaffna/Colombo/20-05-2024');
  await page.locator('li').filter({ hasText: 'New JGP Luxury (L) Route number: 15/87 Kankesanthurai 9:00 PM 20 May Jaffna' }).getByRole('link').click();
  await page.getByRole('checkbox', { name: '9', exact: true }).click();
  await page.getByRole('button', { name: 'F' }).click();
  await page.getByText('Passenger Name Mobile Number').click();
  await page.getByPlaceholder('Enter passenger name').click();
  await page.getByPlaceholder('Enter passenger name').fill('LoLO');
  await page.getByText('Mobile Number').click();
  await page.getByPlaceholder('234 5678').click();
  await page.getByPlaceholder('234 5678').fill('0779731605');
  await page.locator('div').filter({ hasText: 'Boarding Place' }).nth(4).click();
  await page.getByText('Boarding Place Manipay Yard').click();
  await page.locator('.selectize-input').first().click();
  await page.locator('.selectize-input').first().click();
  await page.locator('.selectize-input').first().click();
  await page.getByPlaceholder('Select your boarding point').click();
  await page.locator('.selectize-input').first().click();
  await page.locator('.selectize-input').first().click();
  await page.locator('div:nth-child(6) > .col-xs-12 > .selectize-control').click();
  await page.getByText('Chillaw - 3:30 AM').click();
  await page.locator('.selectize-input').first().click();
  await page.getByText('Manipay Food City - 7:32 PM').click();
  await page.getByRole('button', { name: 'Continue to pay' }).click();
  await page.getByRole('button', { name: 'Confirm and pay' }).click();
  await page.getByTestId('pomelopay-button').click();
  await page.getByLabel('I agree to the terms and').check();
  await page.getByTestId('pomelopay-button').click();
  //await page.locator('div').filter({ hasText: /^Visa\/Mastercard$/ }).nth(1).click();
  await page.getByText('Visa/Mastercard').click();
  await page.getByPlaceholder('Name on card').click();
  await page.getByPlaceholder('Name on card').fill('WWE');
  await page.getByPlaceholder('Card Number').click();
  await page.getByPlaceholder('Card Number').fill('5045 4717 7155 ');
  await page.getByPlaceholder('MM/YY').click();
  await page.getByPlaceholder('MM/YY').fill('01/23');
  await page.getByPlaceholder('CVV').click();
  await page.getByPlaceholder('CVV').fill('444');
});