import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://test3.busseat.lk/');
  await page.locator('.selectize-control > .form-control').first().click();
  await page.getByPlaceholder('Enter your departure station').fill('Jaff');
  await page.getByText('Jaffna').nth(2).click();
  await page.locator('div:nth-child(2) > .form-group > .selectize-control > .form-control').click();
  await page.getByPlaceholder('Enter your arrival station').fill('Co');
  await page.getByText('Colombo', { exact: true }).nth(2).click();
  await page.getByPlaceholder('Select journey date').click();
  await page.getByRole('cell', { name: '14' }).click();
  await page.getByRole('button', { name: 'Find Buses' }).click();
  await page.locator('li').filter({ hasText: 'Colombo Bus 1 Super Luxury (' }).getByRole('link').click();
  await page.getByRole('checkbox', { name: '5', exact: true }).click();
  await page.getByRole('button', { name: 'F' }).click();
  await page.getByPlaceholder('Enter passenger name').click();
  await page.getByPlaceholder('Enter passenger name').fill('Ana De Armas');
  await page.getByPlaceholder('234 5678').click();
  await page.getByPlaceholder('234 5678').fill('0779731605');
  await page.getByPlaceholder('Select your boarding point').click();
  await page.getByText('Bastian Jn - 10:05 PM').click();
  await page.getByPlaceholder('Select your destination point').click();
  await page.getByText('Mount Lavania - 5:50 AM').click();
  await page.getByRole('button', { name: 'Continue to pay' }).click();
  await page.getByRole('button', { name: 'Confirm and pay' }).click();
  await page.getByLabel('I agree to the terms and').check();
  await page.getByTestId('pomelopay-button').click();
  await page.getByText('Visa/Mastercard').click();
  await page.getByPlaceholder('Card Number').click();
  await page.getByPlaceholder('Card Number').fill('5099 9930 0011 6591');
  await page.getByPlaceholder('Card Number').click();
  await page.getByPlaceholder('Card Number').dblclick();
  await page.getByPlaceholder('Card Number').click();
  await page.getByPlaceholder('Card Number').press('ArrowRight');
  await page.getByPlaceholder('Card Number').press('ArrowRight');
  await page.getByPlaceholder('Card Number').press('ArrowRight');
  await page.getByPlaceholder('Card Number').press('ArrowRight');
  await page.getByPlaceholder('Card Number').press('ArrowRight');
  await page.getByPlaceholder('Card Number').press('ArrowRight');
  await page.getByPlaceholder('Card Number').press('ArrowRight');
  await page.getByPlaceholder('Card Number').press('ArrowRight');
  await page.getByPlaceholder('Card Number').press('ArrowRight');
  await page.getByPlaceholder('Card Number').press('ArrowRight');
  await page.getByPlaceholder('Card Number').fill('5099 9930 0011 6951');
  await page.getByPlaceholder('MM/YY').click();
  await page.getByPlaceholder('MM/YY').fill('03/27');
  await page.getByPlaceholder('CVV').click();
  await page.getByPlaceholder('CVV').fill('986');
  await page.locator('.pp-relative').first().click();
  await page.getByPlaceholder('Name on card').click();
  await page.getByPlaceholder('Name on card').fill('Ana');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.frameLocator('#pp-lightbox-iframe').getByRole('button', { name: 'Submit' }).click();
  await page.goto('https://test3.busseat.lk/booking/20240514.100715.349.001/result');
});