import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://test3.busseat.lk/');
  await page.getByPlaceholder('Enter your departure station').click();
  await page.getByPlaceholder('Enter your departure station').fill('Jaff');
  await page.getByText('Jaffna').nth(2).click();
  await page.getByPlaceholder('Enter your arrival station').click();
  await page.getByPlaceholder('Enter your arrival station').fill('Co');
  await page.getByText('Colombo', { exact: true }).nth(2).click();
  await page.getByPlaceholder('Select journey date').click();
  await page.getByRole('cell', { name: '20', exact: true }).click();
  await page.getByRole('button', { name: 'Find Buses' }).click();
  await page.locator('li').filter({ hasText: 'Colombo Bus 1 Super Luxury (' }).getByRole('link').click();
  await page.getByRole('checkbox', { name: '4', exact: true }).click();
  await page.getByRole('button', { name: 'F' }).click();
  await page.getByPlaceholder('Enter passenger name').click();
  await page.getByPlaceholder('Enter passenger name').fill('Kokulan');
  await page.getByPlaceholder('234 5678').click();
  await page.getByPlaceholder('234 5678').fill('0779731605');
  await page.locator('.selectize-input').first().click();
  await page.getByPlaceholder('user@domain.com').click();
  await page.getByPlaceholder('Select your boarding point').click();
  await page.getByText('Manipay BOC - 7:31 PM').click();
  await page.getByPlaceholder('Select your destination point').click();
  await page.getByText('Ja Ela - 4:50 AM').click();
  await page.getByLabel('Reuse Credits').check();
  await page.getByLabel('Reuse Credits').uncheck();
  await page.getByRole('button', { name: 'Continue to pay' }).click();
  await page.getByRole('button', { name: 'Confirm and pay' }).click();
  await page.goto('https://transaction.geniebiz.lk/664b14d6ef1d306aac08b50c?');
  await page.goto('https://transaction.geniebiz.lk/664b14d6ef1d306aac08b50c/paynow');
  await page.getByLabel('I agree to the terms and').check();
  await page.getByTestId('pomelopay-button').click();
  await page.getByText('Visa/Mastercard').click();
  await page.locator('.pp-relative').first().click();
  await page.getByPlaceholder('Name on card').click();
  await page.getByPlaceholder('Name on card').fill('Kokul');
  await page.getByPlaceholder('Card Number').click();
  await page.getByPlaceholder('Card Number').fill('5055 4454 45454');
  await page.getByPlaceholder('MM/YY').click();
  await page.getByPlaceholder('MM/YY').fill('12/28');
  await page.getByPlaceholder('CVV').click();
  await page.getByPlaceholder('CVV').fill('444');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.goto('https://transaction.geniebiz.lk/664b14d6ef1d306aac08b50c/payment-processing?error=1');
  await page.goto('https://transaction.geniebiz.lk/664b14d6ef1d306aac08b50c?error=1');
  await page.goto('https://transaction.geniebiz.lk/664b14d6ef1d306aac08b50c/paynow');
});