import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://test3.busseat.lk/');
  await page.getByPlaceholder('Enter your departure station').click();
  await page.getByPlaceholder('Enter your departure station').fill('Jaffna');
  await page.getByPlaceholder('Enter your arrival station').click();
  await page.getByPlaceholder('Enter your arrival station').fill('Colo');
  await page.getByText('Colombo', { exact: true }).nth(1).click();
  await page.getByPlaceholder('Select journey date').click();
  await page.getByRole('cell', { name: '15' }).click();
  await page.getByRole('button', { name: 'Find Buses' }).click();
  await page.getByPlaceholder('Enter your departure station').fill('Jaff');
  await page.getByText('Jaffna').nth(2).click();
  await page.getByPlaceholder('Enter your arrival station').click();
  await page.getByPlaceholder('Enter your arrival station').fill('Colo');
  await page.getByText('Colombo', { exact: true }).nth(2).click();
  await page.getByRole('button', { name: 'Find Buses' }).click();
  await page.locator('li').filter({ hasText: 'ABI 11111 Luxury (L) Route' }).getByRole('link').click();
  await page.getByRole('checkbox', { name: '1', exact: true }).click();
  await page.getByRole('button', { name: 'F' }).click();
  await page.getByPlaceholder('Enter passenger name').click();
  await page.getByPlaceholder('Enter passenger name').fill('kokulan');
  await page.getByPlaceholder('234 5678').click();
  await page.getByPlaceholder('234 5678').fill('0779731605');
  await page.locator('.selectize-input').first().click();
  await page.getByText('Jaffna Town - 5:10 AM').click();
  await page.getByPlaceholder('Select your destination point').click();
  await page.getByRole('button', { name: 'Continue to pay' }).click();
  await page.getByText('Kurunegala Bus Stand - 10:10').click();
  await page.getByRole('button', { name: 'Continue to pay' }).click();
  await page.getByRole('button', { name: 'Confirm and pay' }).click();
  await page.goto('https://transaction.uat.geniebiz.lk/6642e1da4728f90c28b2583d?');
  await page.goto('https://transaction.uat.geniebiz.lk/6642e1da4728f90c28b2583d/paynow');
  await page.locator('#checkbox-agreement').click();
  await page.getByTestId('pomelopay-button').click();
  await page.locator('div').filter({ hasText: /^Visa\/Mastercard$/ }).nth(1).click();
  await page.getByPlaceholder('Name on card').click();
  await page.getByPlaceholder('Name on card').fill('SHAM');
  await page.getByPlaceholder('Card Number').click();
  await page.getByPlaceholder('Card Number').fill('5099 9930 0011 6951');
  await page.getByPlaceholder('MM/YY').click();
  await page.getByPlaceholder('MM/YY').fill('03/27');
  await page.getByPlaceholder('CVV').click();
  await page.getByPlaceholder('CVV').fill('986');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.frameLocator('#pp-lightbox-iframe').getByRole('button', { name: 'Submit' }).click();
  await page.goto('https://transaction.uat.geniebiz.lk/6642e1da4728f90c28b2583d/completed');
  await page.goto('https://test3.busseat.lk/booking/20240514.093021.364.001/result');
});