import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://test.sharonbuslines.ca/');
  await page.locator('#menu').getByRole('link', { name: 'Get quote now' }).click();
  await page.getByPlaceholder('Enter your company name').click();
  await page.getByPlaceholder('Enter your company name').fill('Aitken Spence ');
  await page.getByPlaceholder('Enter your name').click();
  await page.getByPlaceholder('Enter your name').fill('');
  await page.getByPlaceholder('Enter your name').press('CapsLock');
  await page.getByPlaceholder('Enter your name').press('CapsLock');
  await page.getByPlaceholder('Enter your name').fill('Robert Lewandoski');
  await page.getByPlaceholder('Enter your phone number, ex +').click();
  await page.getByPlaceholder('Enter your phone number, ex +').fill('+');
  await page.getByPlaceholder('Enter your phone number, ex +').press('PageUp');
  await page.getByPlaceholder('Enter your phone number, ex +').press('NumLock');
  await page.getByPlaceholder('Enter your phone number, ex +').fill('+94779731605');
  await page.getByPlaceholder('Enter your email').click();
  await page.getByPlaceholder('Enter your email').fill('kokulan@3axislabs.com');
  await page.getByPlaceholder('Enter your email').click();
  await page.getByPlaceholder('Enter your email').dblclick();
  await page.getByPlaceholder('Enter your email').click();
  await page.getByPlaceholder('Enter your email').click();
  await page.getByPlaceholder('Enter your email').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email').press('ArrowRight');
  await page.getByPlaceholder('Enter your email').fill('vijay@3axislabs.com');
  await page.getByPlaceholder('Enter your address').click();
  await page.getByPlaceholder('Enter your address').fill('East Coast road Markham Canada');
  await page.getByPlaceholder('Enter your city').click();
  await page.getByPlaceholder('Enter your city').fill('Markham');
  await page.getByPlaceholder('Enter your state').click();
  await page.getByPlaceholder('Enter your state').fill('Ontario');
  await page.getByPlaceholder('Enter postal code').click();
  await page.getByPlaceholder('Enter postal code').fill('LK2 R8T');
  await page.getByPlaceholder('Enter number of passengers').click();
  await page.getByPlaceholder('Enter number of passengers').fill('42');
  await page.getByLabel('Round trip').check();
  await page.getByPlaceholder('Enter Pickup location').click();
  await page.getByPlaceholder('Enter Pickup location').fill('Markham City C');
  await page.getByPlaceholder('Enter Pickup location').click();
  await page.getByPlaceholder('Enter Pickup location').fill('Markham City Center');
  await page.locator('#departure-date').fill('2024-03-27');
  await page.locator('#departure-time').click();
  await page.locator('#departure-time').fill('09:43');
  await page.getByText('Add another pickup location').click();
  await page.getByRole('textbox', { name: 'Enter Pickup location' }).click();
  await page.getByRole('textbox', { name: 'Enter Pickup location' }).fill('A1');
  await page.getByPlaceholder('Select Date', { exact: true }).fill('2024-03-26');
  await page.getByPlaceholder('Select Time', { exact: true }).click();
  await page.getByPlaceholder('Select Time', { exact: true }).fill('09:47');
  await page.getByPlaceholder('Enter destination').click();
  await page.getByPlaceholder('Enter destination').fill('Vancouver Museum  ');
  await page.locator('#destination-date').fill('2024-03-26');
  await page.locator('#destination-time').click();
  await page.locator('#destination-time').fill('21:50');
  await page.locator('#add-drop-off-location').click();
  await page.getByPlaceholder('Enter Destination', { exact: true }).click();
  await page.getByPlaceholder('Enter Destination', { exact: true }).fill('NT yard');
  await page.locator('#drop-off-location-date0').fill('2024-03-27');
  await page.locator('#drop-off-location-time0').click();
  await page.locator('#drop-off-location-time0').fill('09:44');
  await page.getByLabel('Return To').fill('2024-03-28');
  await page.locator('#returnToTime').click();
  await page.locator('#returnToTime').fill('09:45');
  await page.getByPlaceholder('Enter your note here...').click();
  await page.getByPlaceholder('Enter your note here...').fill('Never');
  //await page.getByPlaceholder('Select file').click();
  //await page.getByPlaceholder('Select file').setInputFiles('A-Z documentation.pdf');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.frameLocator('iframe[name="a-tcuy1fgshi06"]').getByLabel('I\'m not a robot').click();
});